slcd-backend-new/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="SLCD API",
        default_version='v1',
        description="SLCD API built by Efe Roy",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('files/', include('filed.urls', namespace="files")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('api/', include("filed.api.urls")),
    path('api/auth/', include("account.api.urls")),



    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger',
            cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc',
            cache_timeout=0), name='schema-redoc'),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

slcd-backend-new/filed/urls.py

from django.urls import path
from .views import (
    fileList, FileCreateView, AssignAgentView, file_update, file_detail, file_delete,
    delete_verify, verifyDoc, track_progress
)

app_name = "files"

urlpatterns = [
    path('', fileList, name='file-list'),
    # path('landpage/', landingpage, name='land-page'),
    path('create/', FileCreateView.as_view(), name='file-create'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/update/', file_update, name='file-update'),
    path('<int:pk>/', file_detail   , name='file-detail'),
    path('<int:pk>/track_progress', track_progress   , name='track_progress'),
    path('<int:pk>/delete/', file_delete, name='file-delete'),
    path('<int:pk>/verifyDoc/', verifyDoc, name='verifyDoc'),
    path('<int:pk>/delete-verify', delete_verify, name='delete-verify'),
]

slcd-backend-new/account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    is_support = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)

class UserProfile(models.Model):
    # user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    
    def __str__(self):
        return f'Profile for user {self.user.username}'

slcd-backend-new/filed/forms.py
from django import forms
from django.forms import fields
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import File, Agent, Category, VeriyDoc

User = get_user_model()

class FileModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'file_name',
            'file_type',
            'headline',
            'agent',
            # 'identify_holder',
            'passport',
            'estate_reg',
            'phone_number',
            'email',
            'completed',
            'value_delineation',
            'delineation_date',
            'delineation_payment',
            'consecutive_delineation',
            'visited_by',
            'State_type',
            'delivery_date',
            'notification_date'
        )

    def clean_first_name(self):
        data = self.cleaned_data["headline"]
        return data

    def clean(self):
        pass

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.all()
        # agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class FileCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'category',
        )


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
        )

class VerifyDocModelForm(forms.ModelForm):
    class Meta:
        model = VeriyDoc
        fields = (
            'Copia_de_cedula_del_propietario_pasaporte',
            'Certificado_de_tradición_y_libertad',
            'Copia_de_la_escritura',
            'Paz_y_salvo_municipal',
            'Copia_del_impuesto_predial',
            'Certificado_catastral',
            'Planos_arquitectónicos_y_estructurales',
            'Planos_topográficos',
            'CD_o_USB',
            'Copia_de_la_tarjeta_profesional',
            'Formulario_único_nacional',
            'Certificado_de_delineación_y_comprobante_de_pago',
            'Viabilidad_de_energía_y_acueducto',
            'Viabilidad_de_alcantarillado_y_aseo',
            'Certificado_de_sismo_resistencia',
            'Memorias_de_calculo',
            'Estudio_de_suelos',
            'Peritaje_técnico',
            'Plan_de_majo_ambiental',
            'Plan_de_manejo_de_escombros',
            'Plan_de_manejo_de_transito',
            'Avaluó_comercial',
            'Declaración_de_antigüedad',
            'Declaración_de_no_bienes',
            'Declaración_extrajuicio_de_sana_posesión',
            'Copia_de_licencia',
            'Certificado_de_nomenclatura',
            'Certificado_del_sisben',
            'Certificado_de_desplazado',
            'Carta_de_aceptación_por_revisor',
            'Poder_autenticado',
            'Autorización_autenticada',
            'Solicitud',
            'Certificado_financiero',
            'Contrato_de_promesa_de_compraventa'
        )

class ObservationModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'observation',
            'observation_date'
        )
        widgets = {
            'observation_date': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date'
                }),
            'observation': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
                })
        }

class UnderReviewModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'underReview',
            'underReview_date'
        )
        widgets = {
            'underReview_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                })
        }

class ReviewModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'review',
            'review_date'
        )
        widgets = {
            'review_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                })
        }

class NotifiedModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'is_notified',
            'is_notified_date',
            'is_notified_observation'
        )
        NOTIFICATION_CHOICES = (
                ('', 'Select an option'),
                ('Yes', 'Yes'), #First one is the value of select option and second is the displayed value in option
                ('No', 'No'),
                )
        widgets = {
            'is_notified': forms.Select(choices=NOTIFICATION_CHOICES,attrs={'class': 'form-select'}),
            'is_notified_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                }),
            'is_notified_observation': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
                })
        }

class PersonalNotifiedModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'is_personal_notified',
            'is_personal_notified_date',
            'is_personal_notified_observation'
        )
        NOTIFICATION_CHOICES = (
                ('', 'Select an option'),
                ('Yes', 'Yes'), #First one is the value of select option and second is the displayed value in option
                ('No', 'No'),
                )
        widgets = {
            'is_personal_notified': forms.Select(choices=NOTIFICATION_CHOICES,attrs={'class': 'form-select'}),
            'is_personal_notified_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                }),
            'is_personal_notified_observation': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
                })
        }

class DocumentModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'correct_document',
            'correct_document_date'
        )
        DOCUMENT_CHOICES = (
                ('', 'Select an option'),
                ('Yes', 'Yes'), #First one is the value of select option and second is the displayed value in option
                ('No', 'No'),
                )
        widgets = {
            'correct_document': forms.Select(choices=DOCUMENT_CHOICES,attrs={'class': 'form-select'}),
            'correct_document_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                })
        }

class ActProcedureModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'file_name',
            'process_act_num',
            'process_act_num_date',
            'liquidation_value'
        )
        widgets = {
            'file_name' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'process_act_num' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'process_act_num_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                }),
            'liquidation_value': forms.DateInput(attrs={
                'class': 'form-control', 
                })
        }

class PaymentModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'payment',
            'payment_status_date'
        )
        widgets = {
            'payment_status_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                })
        }

class PaymentDocModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'payment_receipt_number',
            'payment_receipt_date',
            'license_value',
            'delineation_tax_value',
        )
        widgets = {
            'payment_receipt_number' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'license_value' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'payment_receipt_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                }),
            'delineation_tax_value': forms.DateInput(attrs={
                'class': 'form-control', 
                })
        }

class ResolutionModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'resolution_number',
            'resolution_date',
        )
        widgets = {
            'resolution_number' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'resolution_date': forms.DateInput(attrs={
                'class': 'form-control', 
                'type': 'date'
                })
        }

class ResolutionNotificationModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = (
            'resolution_notification_date',
        )
        widgets = {

slcd-backend-new/templates/files/assign_agent.html
{% extends "layout.html" %}

{% block content %}

<div class="row" style="height: 70vh;">
    <a class="" href="{% url 'files:file-list' %}">Volver a clientes potenciales</a>
    <div class="">
        <h1 class="text-center">Asignar una agente a esta iniciativa</h1>
    </div>

    <div class="justify-content-center d-flex align-item-center">
        <form method="post" class="">
            {% csrf_token %}
            <label for="id_agent">Agentes:</label>

            <select class="form-select" aria-label="Default select example"  name="agent" required="" id="id_agent">
                <option selected>----------------</option>
                {% for c in form.fields.agent.queryset %}
                    <option value={{c.id}}>{{c.user.username}}</option>
                {% endfor %}
            </select>

            <button type="submit" class="w-100 btn btn-primary mt-4 ">
                Enviar
            </button>
        </form>
    </div>

    
</div>

{% endblock content %}

slcd-backend-new/templates/files/file_create.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
<a class="text-dark btn btn-info shadow-sm mt-3" style="text-decoration: none;" href="{% url 'files:file-list' %}">
    <!-- &#8592 -->
    <i class="bi-arrow-bar-left"></i>
    volver al archivo
</a>

<!-- <form action="" class="mt-5" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit">Submit</button>
</form> -->

<section class="container my-5 shadow bg-white text-dark p-2">
    <form class="row g-3 p-3" method="post"">
            {% csrf_token %}
            <div id=" div_id_file_name" class="col-md-6">
        <label for="id_file_name" class="form-label">Radicado</label>
        <input type="text" name="file_name" maxlength="500" value={{current_num}} class="textinput form-control"
            required="" id="id_file_name">
        </div>
        <div class="col-md-6">
            <label for="inputState" class="form-label">Tipo de solicitud </label>
            <select name="file_type" id="id_file_type" class="form-select">
                <option selected>Choose...</option>
                {% for c in form.fields.file_type.queryset %}
                <option value={{c.id}}>{{c.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-6">
            <label for="id_headline" class="form-label">Titular</label>
            <input type="text" name="headline" class="form-control" maxlength="20" required="" id="id_headline">
        </div>
        <div class="col-md-6">
            <label for="id_passport" class="form-label">Cedule/Pasaporte</label>
            <input type="text" name="passport" maxlength="500" class="textinput form-control" required=""
                id="id_passport">
        </div>
        <div class="col-md-6">
            <label class="form-label" for="id_estate_reg">Matricula Inmobiliaria</label>
            <input type="text" class="form-control" name="estate_reg" maxlength="20" required="" id="id_estate_reg">
        </div>
        <div class="col-md-6">
            <label for="id_phone_number" class="form-label">Telefono y/o Celular </label>
            <input type="text" class="form-control" name="phone_number" maxlength="20" required="" id="id_phone_number">
        </div>
        <div class="col-md-6">
            <label for="id_email" class="form-label">Correo Electronico</label>
            <input type="email" class="form-control" name="email" maxlength="254" required="" id="id_email">
        </div>

        <div id="div_id_value_delineation" class="col-md-6">
            <label for="id_value_delineation" class="form-label">Valor del certificado de delineacion </label>
            <input type="text" name="value_delineation" maxlength="60" class="textinput form-control" required=""
                id="id_value_delineation">
        </div>

        <div id="div_id_delineation_date" class="col-md-6">
            <label for="id_delineation_date" class="form-label">Delineation date</label>
            <input type="date" name="delineation_date" class="datetimeinput form-control" id="id_delineation_date">
        </div>
        <div id="div_id_delineation_payment" class="col-md-6">
            <label for="id_delineation_payment" class="form-label requiredField">Delineation payment </label>
            <input type="text" name="delineation_payment" maxlength="40" class="textinput form-control" required=""
                id="id_delineation_payment">
        </div>
        <div id="div_id_consecutive_delineation" class="col-md-6">
            <label for="id_consecutive_delineation" class="form-label requiredField">Consecutive delineation</label>
            <input type="text" name="consecutive_delineation" maxlength="40" class="textinput form-control" required=""
                id="id_consecutive_delineation">
        </div>
        <div id="div_id_visited_by" class="col-md-6">
            <label for="id_visited_by" class="form-label requiredField">Visited by</label>
            <input type="text" name="visited_by" maxlength="70" class="textinput form-control" required=""
                id="id_visited_by">
        </div>

        <!-- <div class="col-md-6"> 
                <label for="id_identify_holder" class="form-label">Identify holder</label> 
                <input type="text" name="identify_holder" maxlength="500" class="textinput form-control" id="id_identify_holder"> 
            </div> -->

        <div class="col-md-4">
            <label for="inputState" class="form-label">State </label>
            <select name="State_type" id="id_State_type" class="form-select" onchange="toggleDiv(this.value)">
                <option value="" selected="">---------</option>
                <option value="1">Asset</option>
                <option value="2">In Progress</option>
                <option value="3">Does Not Apply</option>
            </select>
        </div>
        <div class="col-md-4">
            <label for="id_phone_number" class="form-label">Billboard Delivery Date </label>
            <input type="date" class="form-control" disabled name="delivery_date" id="id_delivery_date">
        </div>
        <div class="col-md-4">
            <label class="form-label" for="id_estate_reg">Date of Notification</label>
            <input type="date" class="form-control" disabled name="notification_date" id="id_notification_date">
        </div>

        <div class="col-12">
            <button type="submit" class="btn w-100 btn-primary">Submit</button>
        </div>
    </form>
</section>

{% block script %}
<script>
    function toggleDiv(value) {
        var id_notification_date = document.getElementById("id_notification_date");
        var id_delivery_date = document.getElementById("id_delivery_date");
        id_notification_date.disabled = value == 2 ? false : true;
        id_notification_date.value = "";
        if (!id_notification_date.disabled) {
            id_notification_date.focus();
        }
        id_delivery_date.disabled = value == 2 ? false : true;
        id_delivery_date.value = "";
        if (!id_delivery_date.disabled) {
            id_delivery_date.focus();
        }
    }
</script>
{% endblock %}
{% endblock content %}

slcd-backend-new/templates/files/file_update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
        <h4>Actualizar Archivo</h4>
        </div>
    </div>

    <a class="btn shadow-sm my-3" href="{% url 'files:file-list' %}">Ir a Inicio</a>


    <!-- <form action="" method="post">
        {% csrf_token %}
        <div class="container">
            {{form|crispy}}
        </div>
        <button type="submit">Submit</button>
    </form> -->

    <!-- <div class="container">

   
    <div id="div_id_value_delineation" class="mb-3"> 
        <label for="id_value_delineation" class="form-label requiredField">Value delineation </label> 
        <input type="text" name="value_delineation" value="asasas" maxlength="60" class="textinput form-control" required="" id="id_value_delineation"> 
    </div> 
    <div id="div_id_delineation_date" class="mb-3"> 
        <label for="id_delineation_date" class="form-label">Delineation date</label> 
        <input type="text" name="delineation_date" value="2023-03-04 00:00:00" class="datetimeinput form-control" id="id_delineation_date"> 
    </div> 
    <div id="div_id_delineation_payment" class="mb-3"> 
        <label for="id_delineation_payment" class="form-label requiredField">Delineation payment</label> 
        <input type="text" name="delineation_payment" value="2000" maxlength="40" class="textinput form-control" required="" id="id_delineation_payment"> 
    </div> 
    <div id="div_id_consecutive_delineation" class="mb-3"> 
        <label for="id_consecutive_delineation" class="form-label requiredField">Consecutive delineation </label> 
        <input type="text" name="consecutive_delineation" value="assas" maxlength="40" class="textinput form-control" required="" id="id_consecutive_delineation"> 
    </div> 
    <div id="div_id_visited_by" class="mb-3"> 
        <label for="id_visited_by" class="form-label requiredField">Visited by </label> 
        <input type="text" name="visited_by" value="emeritus" maxlength="70" class="textinput form-control" required="" id="id_visited_by"> 
    </div> 
    <div id="div_id_State_type" class="mb-3"> 
        <label for="id_State_type" class="form-label">State type</label> 
        <select name="State_type" class="select form-select" id="id_State_type"> <option value="">---------</option> <option value="1">Asset</option> <option value="2" selected="">In Progress</option> <option value="3">Does Not Apply</option>

        </select> 
    </div> 
    <div id="div_id_delivery_date" class="mb-3"> 
        <label for="id_delivery_date" class="form-label">Delivery date</label> 
        <input type="text" name="delivery_date" value="2023-03-04 00:00:00" class="datetimeinput form-control" id="id_delivery_date"> 
    </div> 
    <div id="div_id_notification_date" class="mb-3"> 
        <label for="id_notification_date" class="form-label">Notification date</label> 
        <input type="text" name="notification_date" value="2023-02-23 00:00:00" class="datetimeinput form-control" id="id_notification_date"> 
    </div>

    </div> -->

<form action="" class="container shadow bg-white p-2" method="post">
    {% csrf_token %}
    <div class="row g-3 p-5">
        <div id="div_id_file_name" class="mb-3 col-md-6"> 
            <label for="id_file_name" class="form-label">Nombre del archivo </label> 
            {{form.file_name}}
        </div> 
        <div id="div_id_file_type" class="col-md-6 mb-3"> 
            <label for="id_file_type" class="form-label">Tipo de solicitud </label>
            {{form.file_type}}
        </div> 
        <div id="div_id_headline" class="col-md-6 mb-3"> 
            <label for="id_headline" class="form-label requiredField">Titular  </label> 
            {{form.headline}}
        </div> 

        <div id="div_id_agent" class="col-md-6 mb-3 d-none"> 
            <label for="id_agent" class="form-label">Agente</label> 
            {{form.agent}}
        </div> 

        <div id="div_id_passport" class="mb-3 col-md-6"> 
            <label for="id_passport" class="form-label requiredField">Passport </label> 
            {{form.passport}}
        </div> 

        <div id="div_id_identify_holder" class="col-md-6 mb-3 d-none"> 
            <label for="id_identify_holder" class="form-label requiredField">Identificación del titular  </label> 
            {{form.identify_holder}}
        </div> 
        <div id="div_id_estate_reg" class="col-md-6 mb-3"> 
            <label for="id_estate_reg" class="form-label requiredField">Matricula Inmobiliaria </label> 
            {{form.estate_reg}}
        </div> 
        <div id="div_id_phone_number" class="col-md-6 mb-3"> 
            <label for="id_phone_number" class="form-label requiredField">Teléfono y/o Celular </label> 
            {{form.phone_number}}        
        </div> 
        <div id="div_id_email" class="col-md-6 mb-3"> 
            <label for="id_email" class="form-label requiredField"> Correo Electronico </label> 
            {{form.email}}
        </div>
        
        <div id="div_id_completed" class="mb-3 d-none"> 
            {{form.completed}}
            <label for="id_completed" class="form-check-label"> Completedo </label> 
        </div> 

        <div id="div_id_value_delineation" class="col-md-6"> 
            <label for="id_value_delineation" class="form-label requiredField">Valor de delineación </label> 
            {{form.value_delineation}}
        </div> 
        <div id="div_id_delineation_date" class="col-md-6"> 
            <label for="id_delineation_date" class="form-label">Fecha de delineación</label> 
            {{form.delineation_date}}
        </div> 
        <div id="div_id_delineation_payment" class="col-md-6"> 
            <label for="id_delineation_payment" class="form-label requiredField">pago de delineación</label> 
            {{form.delineation_payment}}
        </div> 
        <div id="div_id_consecutive_delineation" class="col-md-6"> 
            <label for="id_consecutive_delineation" class="form-label requiredField">Consecutivo de delineación </label> 
            {{form.consecutive_delineation}}
        </div> 
        <div id="div_id_visited_by" class="col-md-6"> 
            <label for="id_visited_by" class="form-label requiredField">Visitado por </label> 
            {{form.visited_by}}
        </div> 
        <div id="div_id_State_type" class="col-md-4"> 
            <label for="id_State_type" class="form-label">Tipo de estado</label> 
            {{form.State_type}}
        </div> 
        <div id="div_id_delivery_date" class="col-md-4"> 
            <label for="id_delivery_date" class="form-label">Fecha de entrega</label> 
            {{form.delivery_date}}
        </div> 
        <div id="div_id_notification_date" class="col-md-4"> 
            <label for="id_notification_date" class="form-label">Fecha de notificación</label> 
            {{form.notification_date}}
        </div>


    </div>
    <button type="submit" class="w-100 btn btn-primary">Submit</button>
 </form>

    <div class="my-5 text-center border">
        <a href="{% url 'files:file-delete' file.pk %}" class="btn w-100 btn-danger">
            Delete
        </a>
    </div>
</div>

{% endblock content %}

slcd-backend-new/templates/files/lead_delete.html
{% extends "layout.html" %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'files:file-list' %}">Volver a los archivos</a>
    </div>
    <h1 class="text-3xl text-gray-800">¿Estás segura de que quieres eliminar este archivo?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Enviar</button>
    </form>
</div>
{% endblock content %}