slcd-backend-new/agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
    AgentUpdateView, SupportCreateView, Agent_Delete, activate
)


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', Agent_Delete, name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('support/', SupportCreateView.as_view(), name='support-create'),
    
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    
]

slcd-backend-new/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="SLCD API",
        default_version='v1',
        description="SLCD API built by Efe Roy",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('files/', include('filed.urls', namespace="files")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('api/', include("filed.api.urls")),
    path('api/auth/', include("account.api.urls")),



    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger',
            cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc',
            cache_timeout=0), name='schema-redoc'),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

slcd-backend-new/agents/models.py
from django.db import models

# Create your models here.

slcd-backend-new/filed/models.py
from django.db import models
from account.models import UserProfile, User


class FileManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class File(models.Model):
    file_name = models.CharField(max_length=500)
    file_date_added = models.DateField(auto_now_add=True)
    headline = models.CharField(max_length=20)
    passport = models.CharField(max_length=500)
    identify_holder = models.CharField(max_length=500,  null=True, blank=True)
    estate_reg = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    value_delineation = models.CharField(max_length=60)
    delineation_date = models.DateField(null=True, blank=True)
    delineation_payment = models.CharField(max_length=40)
    consecutive_delineation = models.CharField(max_length=40)
    visited_by = models.CharField(max_length=70)
    State_type = models.ForeignKey("StateType", null=True, blank=True, on_delete=models.SET_NULL)
    delivery_date = models.DateField(null=True, blank=True)
    notification_date = models.DateField(null=True, blank=True)
    
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    completed = models.BooleanField(default=False)

    observation = models.TextField(max_length=1000, null=True, blank=True)
    observation_date = models.DateField(null=True, blank=True)

    review = models.BooleanField(default=False)
    review_date = models.DateField(null=True, blank=True)

    underReview = models.BooleanField(default=False)
    underReview_date = models.DateField(null=True, blank=True)

    is_notified = models.CharField(max_length=20, blank=True, null=True)
    is_notified_date = models.DateField(null=True, blank=True)
    is_notified_observation = models.TextField(max_length=1000, null=True, blank=True)

    correct_document = models.CharField(max_length=20, blank=True, null=True)
    correct_document_date = models.DateField(null=True, blank=True)

    process_act_num = models.CharField(max_length=500, null=True, blank=True)
    process_act_num_date = models.DateField(null=True, blank=True)
    liquidation_value = models.CharField(max_length=500, null=True, blank=True)

    is_personal_notified = models.CharField(max_length=20, blank=True, null=True)
    is_personal_notified_date = models.DateField(null=True, blank=True)
    is_personal_notified_observation = models.TextField(max_length=1000, null=True, blank=True)

    # payment form
    payment = models.BooleanField(default=False)
    payment_status_date = models.DateField(null=True, blank=True)

    payment_receipt_number = models.CharField(max_length=500, null=True, blank=True)
    payment_receipt_date = models.DateField(null=True, blank=True)
    license_value = models.CharField(max_length=500, null=True, blank=True)
    delineation_tax_value = models.CharField(max_length=500, null=True, blank=True)

    # GENERATE RESOLUTION
    resolution_number = models.CharField(max_length=500, null=True, blank=True)
    resolution_date = models.DateField(null=True, blank=True)
    resolution_notification_date = models.DateField(null=True, blank=True)

    updatedAt = models.DateField(null=True, blank=True)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    file_type = models.ForeignKey("FileType", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name="files", null=True, blank=True, on_delete=models.SET_NULL)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    objects = FileManager()

    def __str__(self):
        return f"{self.headline}"
        # return f"{self.headline} {self.phone_number}"


class VeriyDoc(models.Model):
    filev = models.ForeignKey("File", related_name="verifyDoc", on_delete=models.CASCADE)

    Copia_de_cedula_del_propietario_pasaporte = models.BooleanField(default=False)
    Certificado_de_tradición_y_libertad = models.BooleanField(default=False)
    Copia_de_la_escritura = models.BooleanField(default=False)
    Paz_y_salvo_municipal = models.BooleanField(default=False)
    Copia_del_impuesto_predial = models.BooleanField(default=False)
    Certificado_catastral = models.BooleanField(default=False)
    Planos_arquitectónicos_y_estructurales = models.BooleanField(default=False)
    Planos_topográficos = models.BooleanField(default=False)
    CD_o_USB = models.BooleanField(default=False)
    Copia_de_la_tarjeta_profesional = models.BooleanField(default=False)
    Formulario_único_nacional = models.BooleanField(default=False)
    Certificado_de_delineación_y_comprobante_de_pago = models.BooleanField(default=False)
    Viabilidad_de_energía_y_acueducto  = models.BooleanField(default=False)
    Viabilidad_de_alcantarillado_y_aseo  = models.BooleanField(default=False)
    Certificado_de_sismo_resistencia  = models.BooleanField(default=False)
    Memorias_de_calculo  = models.BooleanField(default=False)
    Estudio_de_suelos  = models.BooleanField(default=False)
    Peritaje_técnico  = models.BooleanField(default=False)
    Plan_de_majo_ambiental  = models.BooleanField(default=False)
    Plan_de_manejo_de_escombros  = models.BooleanField(default=False)
    Plan_de_manejo_de_transito  = models.BooleanField(default=False)
    Avaluó_comercial  = models.BooleanField(default=False)
    Declaración_de_antigüedad   = models.BooleanField(default=False)
    Declaración_de_no_bienes   = models.BooleanField(default=False)
    Declaración_extrajuicio_de_sana_posesión   = models.BooleanField(default=False)
    Copia_de_licencia   = models.BooleanField(default=False)
    Certificado_de_nomenclatura   = models.BooleanField(default=False)
    Certificado_del_sisben   = models.BooleanField(default=False)
    Certificado_de_desplazado   = models.BooleanField(default=False)
    Carta_de_aceptación_por_revisor   = models.BooleanField(default=False)
    Poder_autenticado   = models.BooleanField(default=False)
    Autorización_autenticada    = models.BooleanField(default=False)
    Solicitud = models.BooleanField(default=False)
    Certificado_financiero    = models.BooleanField(default=False)
    Contrato_de_promesa_de_compraventa = models.BooleanField(default=False)

    # observation = models.TextField(max_length=1000, null=True, blank=True)
    # observation_date = models.DateField(null=True, blank=True)

    # review = models.BooleanField(default=False)
    # review_date = models.DateField(null=True, blank=True)

    # underReview = models.BooleanField(default=False)
    # underReview_date = models.DateField(null=True, blank=True)


class FileType(models.Model):
    name = models.CharField(max_length=110)

    def __str__(self):
        return self.name


class StateType(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name



class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_username(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)  # New, Contacted, Converted, Unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

slcd-backend-new/agents/views.py
import random

from django.core.mail import send_mail
from django.core.mail import EmailMessage

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse, render, redirect
from filed.models import Agent
from .forms import AgentModelForm, RemoveUser
from account.models import UserProfile
from django.conf import settings

from django.contrib import messages
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string

from django.contrib.auth import login, authenticate
# from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from .tokens import account_activation_token


from django.contrib.auth import get_user_model
User = get_user_model()


class AgentListView(LoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.is_agent = True
        user.is_organisor = False
        # pasw = random.randint(0, 1000000)
        # user.set_password(f"{pasw}")
        user.set_password(f"test12345")
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )

        messages.success(self.request, "Agent created successfully")

        # ====== send email notification ===== #
        email = user.email
        subject= 'Activate Your SLDC Account'
        # message= f"password:- test12345 You were added as an agent on SLCD_CRM. Please come login to start working. "
        message = render_to_string('account/account_activation_email.html', {
                'user': user,
                'domain': '127.0.0.1:8000',
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
        from_email= settings.EMAIL_HOST_USER
        recipient_list=[email]
        # send_mail(subject, message, from_email, recipient_list, fail_silently=False)


        html_version = 'account/account_activation_email.html'

        html_message = render_to_string(html_version, {
                'user': user,
                'domain': '127.0.0.1:8000',
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

        message = EmailMessage(subject, html_message, from_email, [email])
        message.content_subtype = 'html' # this is required because there is no plain text email version
        message.send()

        return super(AgentCreateView, self).form_valid(form)


def activate(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):

    uid = force_bytes(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
    #user = User.objects.get(pk=uid)
    try:

        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')

        return render(request, 'account/homeacttive.html',{'subject': user})
    else:
        return render(request, 'account/register.html')

class SupportCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "agents/support_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.is_support = True
        user.is_organisor = False
        # pasw = random.randint(0, 1000000)
        # user.set_password(f"{pasw}")
        user.set_password(f"test12345")
        # user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        # Agent.objects.create(
        #     user=user,
        #     organisation=self.request.user.userprofile
        # )
        # Create the user profile
        UserProfile.objects.create(user=user)

        messages.success(self.request, "Support created successfully")


        # ====== send email notification ===== #
        email = user.email
        subject= 'You are invited to be an support'
        # message= f"password:- test12345 You were added as an support on SLCD_CRM. Please come login to start working. "
        message = render_to_string('account/account_activation_email.html', {
                'user': user,
                'domain': '127.0.0.1:8000',
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
        from_email= settings.EMAIL_HOST_USER
        recipient_list=[email]

        html_version = 'account/account_activation_email.html'

        html_message = render_to_string(html_version, {
                'user': user,
                'domain': '127.0.0.1:8000',
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

        message = EmailMessage(subject, html_message, from_email, [email])
        message.content_subtype = 'html' # this is required because there is no plain text email version
        message.send()
        return super(SupportCreateView, self).form_valid(form)


class AgentDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


def Agent_Delete(request, pk):  
    print(pk)
    try:
        u = User.objects.get(id = pk)
        u.delete()
        messages.success(request, "The user is deleted")            

    except User.DoesNotExist:
        messages.error(request, "Agent User doesnot exist")    
        return render(request, 'agents/agent_list.htmll')

    except Exception as e: 
        return render(request, 'agents/agent_list.html',{'err':e.message})

    return redirect('agents:agent-list')

slcd-backend-new/templates/agents/agent_create.html
{% extends "layout.html" %}

{% block content %}

<div class="">
        <a class="text-dark btn shadow-sm mt-2" style="text-decoration: none;" href="{% url 'agents:agent-list' %}">Volver a los agentes</a>
</div>

<section class="d-flex align-items-center my-4 justify-content-center" style="height: 100%;">
    <div class="rounded shadow" style="width: 360px; height: min-content; padding: 20px; ">
    
        <h1 class="text-center fs-3 mb-2">¡Crea una nueva agente!</h1>
        
        {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.errors }}
            </div>
        {% endif %}

        <form method="post" class="needs-validation">
            {% csrf_token %}
            <div class="form-group was-validated">
                <label class="form-label" for="email">Correo Electronico</label>
                {{form.email}}
                <!-- <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">  -->

                <div class="invalid-feedback">
                    Por favor, introduzca su dirección de correo electrónico
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="Username">Userario</label>
                {{form.username}}
                <!-- <input type="text" name="username" maxlength="150" class="form-control" required id="id_username">  -->
                <div class="invalid-feedback">
                    Por favor, ingrese su nombre de usuario
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">Nombre</label>
                {{form.first_name}}
                <!-- <input type="text" name="first_name" maxlength="150" class="form-control" required id="id_first_name">  -->
                <div class="invalid-feedback">
                    Por favor, introduzca su nombre
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">Apellidos</label>
                {{form.last_name}}
                <!-- <input type="text" name="last_name" maxlength="150" class="form-control" required id="id_last_name">  -->
                <div class="invalid-feedback">
                    Por favor, introduzca sus apellidos
                </div>
            </div>
            <input class="btn btn-success w-100 mt-3" type="submit" value="Submit">
        </form>

        <!-- {{form}} -->
    
    </div>
</section>
{% endblock content %}

slcd-backend-new/templates/agents/agent_delete.html
{% extends "layout.html" %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}">Volver a los agentes</a>
    </div>
    <h1 class="text-3xl text-gray-800">¿Está seguro de que desea eliminar este agente?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Enviar</button>
    </form>
    <div class="py-5 mt-5">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-detail' object.pk %}">Cancelar</a>
    </div>
</div>
{% endblock content %}

slcd-backend-new/templates/agents/agent_detail.html
{% extends "layout.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENTES</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Descripción general
                </a>
                <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Actualizar detalles
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Nombre Completo</span>
                <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{ agent.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Correo Electronico</span>
                <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

slcd-backend-new/templates/agents/agent_list.html
{% extends "layout.html" %}

{% block content %}
<h1 class="text-center">Agentes</h1>
    <div class="d-flex justify-content-around align-items-center py-3 mt-5">
        <div>
            <a class="btn shadow-sm" style="text-decoration: none;" href="{% url 'agents:support-create' %}">Crear un nuevo soporte</a>
        </div>
        <div>
            <a class="btn shadow-sm" style="text-decoration: none;" href="{% url 'agents:agent-create' %}">Crear un nuevo agente</a>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 my-3">
        <div class="card">
            <div class="card-header">
            <span><i class="bi bi-table me-2"></i></span> Tabla de datos
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table
                id="example"
                class="table data-table"
                style="width: 100%"
                >
                <thead class="bg-light">
                    <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                    </tr>
                </thead>
                    <tbody>
                    {% for agent in object_list %}
                        <tr class="bg-white">
                            <td>
                                {{ agent.user.username }}
                            </td>
                            <td>
                                {{ agent.user.email }}
                            </td>
                            <td>
                                {% if agent.user.is_agent %}    
                                    <!-- Agent -->
                                    responsable
                                {% else %}
                                    <!-- Support -->
                                    Atención al cliente
                                {% endif %}
                            </td>
                            <td>

                                <a href="{% url 'agents:agent-update' agent.pk %}"><i class="material-icons text-warning" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                <!-- <a href="#"><i class="material-icons" title="View" data-toggle="tooltip">&#xE417;</i></a> -->
                                <a data-bs-toggle="modal" href="#deleteEmployeeModal" class="text-danger"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                            
                            </td>

                        </tr>

                        <!-- Delete Modal -->
                        <div class="modal fade" id="deleteEmployeeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Usuario</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-center">
                                    <p>¿Está seguro de que desea eliminar estos usuarios?</p>
                                    <p class="text-warning"><small>Esta acción no se puede deshacer.</small></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'agents:agent-delete' agent.user.id %}" class="btn btn-danger">Eliminar</a>
                                </div>
                                </div>
                            </div>
                        </div>

                    {% empty %}

                        <tr>
                            <td colspan="4" class="text-center">
                                <!-- There are currently no agents -->
                                Actualmente no hay responsable
                            </td>
                        </tr>

                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                    </tr>
                </tfoot>
                </table>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

slcd-backend-new/templates/agents/agent_update.html
{% extends "layout.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENTES</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Descripción general
                </a>
                <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Actualizar detalles
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Enviar</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'agents:agent-delete' agent.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Eliminar
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

slcd-backend-new/templates/agents/support_create.html
{% extends "layout.html" %}

{% block content %}

<div class="">
        <a class="" href="{% url 'agents:agent-list' %}">Volver a los agentes</a>
</div>

<section class="d-flex align-items-center my-4 justify-content-center" style="height: 100%;">
    <div class="rounded shadow" style="width: 360px; height: min-content; padding: 20px; ">
    
        <h1 class="text-center fs-3 mb-2">¡Crea un nuevo soporte!</h1>
        
        {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.errors }}
            </div>
        {% endif %}
        
        <form method="post" class="needs-validation">
            {% csrf_token %}
            <div class="form-group was-validated">
                <label class="form-label" for="email">Dirección de correo electrónico</label>
                {{form.email}}
                <!-- <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">  -->

                <div class="invalid-feedback">
                    Por favor, introduzca su dirección de correo electrónico
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="Username">Nombre de usuario</label>
                {{form.username}}
                <!-- <input type="text" name="username" maxlength="150" class="form-control" required id="id_username">  -->
                <div class="invalid-feedback">
                    Por favor, ingrese su nombre de usuario
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">Nombre</label>
                {{form.first_name}}
                <!-- <input type="text" name="first_name" maxlength="150" class="form-control" required id="id_first_name">  -->
                <div class="invalid-feedback">
                    Por favor, introduzca su nombre
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">Apellidos</label>
                {{form.last_name}}
                <!-- <input type="text" name="last_name" maxlength="150" class="form-control" required id="id_last_name">  -->
                <div class="invalid-feedback">
                    Por favor, introduzca sus apellidos
                </div>
            </div>
            <input class="btn btn-success w-100 mt-3" type="submit" value="Submit">
        </form>
    
    </div>
</section>
{% endblock content %}