slcd-backend-new/agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
    AgentUpdateView, SupportCreateView, Agent_Delete, activate
)


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', Agent_Delete, name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('support/', SupportCreateView.as_view(), name='support-create'),
    
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    
]

slcd-backend-new/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="SLCD API",
        default_version='v1',
        description="SLCD API built by Efe Roy",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('files/', include('filed.urls', namespace="files")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('api/', include("filed.api.urls")),
    path('api/auth/', include("account.api.urls")),



    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger',
            cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc',
            cache_timeout=0), name='schema-redoc'),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

slcd-backend-new/filed/urls.py

from django.urls import path
from .views import (
    fileList, FileCreateView, AssignAgentView, file_update, file_detail, file_delete,
    delete_verify, verifyDoc, track_progress
)

app_name = "files"

urlpatterns = [
    path('', fileList, name='file-list'),
    # path('landpage/', landingpage, name='land-page'),
    path('create/', FileCreateView.as_view(), name='file-create'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/update/', file_update, name='file-update'),
    path('<int:pk>/', file_detail   , name='file-detail'),
    path('<int:pk>/track_progress', track_progress   , name='track_progress'),
    path('<int:pk>/delete/', file_delete, name='file-delete'),
    path('<int:pk>/verifyDoc/', verifyDoc, name='verifyDoc'),
    path('<int:pk>/delete-verify', delete_verify, name='delete-verify'),
]

slcd-backend-new/templates/components/navbar.html
{% load static %}

<!-- top navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white py-1 px-2 ">
  <div class="container-fluid">
    {% if request.user.is_authenticated %}
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="offcanvas"
      data-bs-target="#sidebar"
      aria-controls="offcanvasExample"
    >
      <span class="navbar-toggler-icon" data-bs-target="#sidebar"></span>
    </button>
    {% endif %}
    <a
      class="navbar-brand me-auto ms-lg-0 ms-3 text-uppercase fw-bold"
      href="/"
      >SLCD CRM
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#topNavBar"
      aria-controls="topNavBar"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="topNavBar">
      <ul class="navbar-nav ms-auto">

        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="rounded-circle border d-flex justify-content-center align-items-center" style="width:30px; height:30px" >
            <img class="img-fluid rounded-circle" src="{% static 'images/avatar.svg' %}" alt="Avatar">
            </div>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if request.user.is_organisor  %}
            <li><a class="dropdown-item" href='{% url "edit" %}'>Editar perfil</a></li>
            <li><a class="dropdown-item" href='{% url "password_change" %}'>Cambiar Contraseña</a></li>
            {% endif %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href='{% url "logout" %}'>Cerrar sesión</a></li>
          </ul>
        </li>

        <b class="my-auto">Bienvenido {{ request.user.username }}</b>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'land-page' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a href='{% url "register" %}' class="nav-link">Registrarse</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href='{% url "login" %}'>Iniciar Sesión</a>
            </li>
        {% endif %}


      
      </ul>
    </div>
  </div>
</nav>
<!-- top navigation bar -->


slcd-backend-new/templates/components/sidebar.html
<!-- offcanvas -->
    <div
      class="offcanvas offcanvas-start sidebar-nav border-0"
      tabindex="-1"
      id="sidebar"
      style="background: #063372;"
    >
      <div class="offcanvas-body ">
        <nav class="navbar-dark text-white">
          <ul class="navbar-nav">
            <!-- <li>
              <div class="text-muted small fw-bold text-uppercase px-3">
                CORE
              </div>
            </li> -->
            <li class="mt-2"></li>
            <li>
              <a href='{% url "dashboard" %}' class="nav-link px-3 active">
                <span class="me-2"><i class="bi bi-speedometer2"></i></span>
                <span>Dashboard</span>
              </a>
            </li>
            <li class="my-4"><hr class="dropdown-divider bg-light" /></li>
            <li>
              <div class="text-muted small fw-bold text-uppercase px-3 mb-3">
                Interfaz
              </div>
            </li>
        
            <li>
              <a href="{% url 'files:file-list' %}" class="nav-link px-3">
                <span class="me-2"><i class="bi bi-book-fill"></i></span>
                <span>Archivos</span>
              </a>
            </li>
            {% if request.user.is_organisor %}
            <li>
              <a href="{% url 'agents:agent-list' %}" class="nav-link px-3">
                <span class="me-2"><i class="bi bi-book-fill"></i></span>
                <span>Agentes</span>
              </a>
            </li>
            {% endif %}
            <li class="my-4"><hr class="dropdown-divider bg-light" /></li>
            <li>
              <div class="text-muted small fw-bold text-uppercase px-3 mb-3">
                Complementos
              </div>
            </li>
            <li>
              <a href="#" class="nav-link px-3">
                <span class="me-2"><i class="bi bi-graph-up"></i></span>
                <span>Vacía</span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- offcanvas -->